services:
  postgres:
    # To Connect "docker exec -it postgres_local  psql -U smonte piscineds localhost -W"
    image: postgres:15
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_DB: piscineds
      POSTGRES_USER: smonte
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../:/workspace
    networks:
      - postgres_network

  pgadmin:
    # Connexion
      # Name: postgres_local
      # Host: postgres (nom du service Docker)
      # Port: 5432
      # Database: piscineds
      # Username: smonte
      # Password: mysecretpassword
    image: dpage/pgadmin4:latest
    container_name: pgadmin_local
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - postgres_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
